name: Update

on:
  workflow_dispatch:
  label:
    types:
      - created # for test
  schedule:
      - cron: '30 16 * * 0-4' # 00:30 Beijing time every Monday to Friday

permissions:
  contents: write
  issues: write 

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update papers
      run: |
        python main.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
        branch: 'main'
        commit_message: '✏️ Update papers automatically.'
        files: README.md .github/ISSUE_TEMPLATE.md
        commit_user_name: qhu-ai-climate
        commit_user_email: wuli777@qhu.edu.cn

    - name: Create an issue to notify
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
